### ISSUE TITLE
Incompatibility with Perfect Vision

### ISSUE THREAD

**Issue by ghost91-** [ghost-fvtt/fxmaster#116]
### Expected Behavior

FXMaster and Perfect Vision play together nicely.

### Current Behavior

FXMaster does not function when Perfect Vision is enabled

### Steps to Reproduce

1. Enable both FXMaster and Perfect Vision
2. Try to add an effect for FXMaster
3. See that nothing happens

### Context

https://discord.com/channels/170995199584108546/921212543433850890/921505768073752586

### Version

v1.2.1-rc1

### Foundry VTT Version

0.8.9

### Operating System

-

### Browser / App

Native Electron App, Chrome, Firefox

### Game System

dnd5e

### Relevant Modules

Perfect Vision

**Comment by dev7355608** [comment]
This is something I have to fix. PV patches weather masks (PV combines the weather mask of FXMaster and core, renders it to a texture, and blurs the FXMaster mask so it's looks nice and pretty) and also applies the FXMaster filters differently (PV doesn't apply the filters the layers separately to entire canvas groups instead). I'll release a PV update later today.

**Comment by ghost91-** [comment]
Great, thanks  @dev7355608. I guess blurring the mask is also something I could do for FXMaster. That would probably look nicer than just a hard cut off. Do you have some some code I could reference?

Regarding filters: That's something I will have to investigate anyways (cf. #103). I'll keep in touch with you if I make any changes in that area.

**Comment by ghost91-** [comment]
I'll keep this issue open for now just to track the current state. I will close it as soon as I have seen FXMaster and PV work in harmony in V9.

**Comment by ghost91-** [comment]
One thing I noticed will be incompatible is that I renamed the `apply_to` property of the filter manager. I see that you were using that in PV. I suppose I can add backwards compatibility if that helps you.

**Comment by dev7355608** [comment]
> I guess blurring the mask is also something I could do for FXMaster. That would probably look nicer than just a hard cut off. Do you have some some code I could reference?

It's a little annoying to implement if you want to do it as efficient as possible, i.e. render the texture only if necessary, and dispose the texture if it's no longer needed. Relevant code is [here](https://github.com/dev7355608/perfect-vision/blob/main/scripts/core/weather.js) and [here](https://github.com/dev7355608/perfect-vision/blob/main/scripts/compatibility/fxmaster.js), but I use a lot of custom stuff, so you might want to work with Foundry's `CachedContainer` instead, but this container renders every frame, so it won't be possible to implement it as efficiently as possible. Foundry does it this way, but in PV I replace the occlusion mask and weather mask for that reason to increase performance.

I just noticed that the FXMaster weather mask is never destroyed, which can cause memory leak. Graphics object are required to be destroyed.

> One thing I noticed will be incompatible is that I renamed the apply_to property of the filter manager to filteredLayers. I see that you were using that in PV. I suppose I can add backwards compatibility if that helps you.

I already made the changes, and everything seems to work like it did in v8. I override `FXMASTER.filters.applyFiltersToLayers` now instead of `FXMASTER.filters.activate/update`.

**Comment by ghost91-** [comment]
> I just noticed that the FXMaster weather mask is never destroyed, which can cause memory leak. Graphics object are required to be destroyed.

Thanks, I will address this.

> > One thing I noticed will be incompatible is that I renamed the apply_to property of the filter manager to filteredLayers. I see that you were using that in PV. I suppose I can add backwards compatibility if that helps you.
> 
> I already made the changes, and everything seems to work like it did in v8. I override `FXMASTER.filters.applyFiltersToLayers` now instead of `FXMASTER.filters.activate/update`.

That's good, I'll add the backwards compatibility anyways, just to be safe. Others could have been accessing it, too.

I also noticed that you seem to be adjusting the order in which filters are applied based on their ids (checking for things like `"core_underwater"` etc.). Do i understand correctly that you actually want to adjust the order based on the type of effect? If so, this won't work correctly for filters that users create via macros because they will have arbitrary ids. I would suggest to use instanceof checks instead, e.g.
```js
if (key === "core_underwater")
```
would become
```js
if(filter instanceof CONFIG.fxmaster.filters.underwater)
```

**Comment by dev7355608** [comment]
The underwater filter is the only one that effects the scene (without UI elements) as well as overlays (grid, token borders, etc). I assume other filters shouldn't effect UI elements. I apply core_predator and core_oldfilm after other filters because it made mode sense to me. Can the order be changed somehow by the user? I see that I reverse the order of the filters. And I newer considered custom filters. I'll change the checks.

**Comment by ghost91-** [comment]
No, the user can't change the order. It's actually more or less random right now in FXMaster because it uses `Object.values` on the `filters` object. I should probably address that in some way at some point.

**Comment by dev7355608** [comment]
Ah, I forgot the important reason why I append and prepend selectively: PV's monochrome filter sits in between. The monochrome filter should be applied after all filters except for filters like predator and oldfilm because those are not really effects in the scene, but screen effects (the monochrome filter should ruin the sepia effect of the oldfilm filter).

I'm going to respect the order from now on, but still insert oldfilm and predator after PV's monochrome filter.

**Comment by ghost91-** [comment]
Backwards compatibility for PV 2.10.8 has been added (d9bba42e4fc5ae367ddf8e20917c31eeb777d0b2, 82007b95af7434a9113941bc6e82edfdc27f9448) and the version of PV for foundry V9 also is compatible as noted above.
