### ISSUE TITLE
Cloud Speed and scale in 2.1.1 much greater than 1.2.1

### ISSUE THREAD

**Issue by JavaShipped** [ghost-fvtt/fxmaster#151]
### Expected Behavior

FX 1.2.1 Settings
``` Scale: 0.7
Direction: 230
Speed: 50
Density: 80
```

Slow rolling clouds from bottom right to top left. 

### Current Behavior

FX 2.1.1 Settings:

```
Scale: 0.1
Direction: 250
Speed: 0.1
```

Clouds moving WAY too fast and scale is way off (too big). Scale 0.7 covers my entire canvass.  

### Steps to Reproduce

The only thing that changed is I moved my install from my local machine to my server. Then updated the modules. 

Update to the new FX Master. 

### Context

This is a video of the two instances as an example: 
https://imgur.com/a/JidU41Y

### Version

2.1.1

### Foundry VTT Version

0.8.9

### Operating System

Window 10

### Browser / App

Native Electron App, Firefox

### Game System

DnD 5e

**Comment by ghost91-** [comment]
Thanks for the report. I don't actually think this is a bug, it's probably due to the following:

In 1.2.1, the scale and speed didn't take the grid size into account. Now they do. The point of doing this is so that the settings are more consistent across scenes. In theory, the settings should have been migrated so that the effects look the same as previously. But in order to not display huge amounts of decimals, the migration rounds the scale and speed values to 1 decimal. What most likely happened in your case is that you were using scale and speed values that when migrated according to the grid size become lower than than 0.1 but then are rounded up to 0.1.

To solve this, there are 2 options:
1. I adjust the scale and speed sliders to allow lower values (probably down to 0.01 instead of 0.1). That's a reasonable feature request. I would also adjust the migration to round to 2 decimals then, but this will only affect scenes that are migrated after that change has been released. You would need to adjust it manually in your scene, I'm afraid.
2. For the time being, you can try adjusting the grid size of that scene. making it smaller should reduce the size and speed of the clouds. As it's world map and you are not displaying the grid, I would assume the grid size doesn't matter to you. If it does, you will unfortunately have to wait for the first solution.

**Comment by JavaShipped** [comment]
Thanks for the ultra quick response!

> Could you send me an export of that scene, including the background image?

Sure thing - how might I go about doing that? Is there a export button or do I need a module!

> Actually, could it be that you are using a huge grid size with that scene?

Wowza! You're spot on here. The grid size is actually huge for (1920) for some insane reason that probably made sense in my head when I made that scene a year ago. 

My other gridless scens are made with a 'normal' grid size of 100 so nothing else really changed.

For the most part this is actually just a hangover from me setting everything up way back when I didn't really know anything about anything in foundry. My 'bug' is in reality a user error, it might just be handy to add a disclaimer in the patchnotes or something, so people like me aren't as stumped if their gridless scenes get messed up a little bit. Saves you a bit of work!

**Comment by JavaShipped** [comment]
> So, reducing the grid size solves your issue?

Yep, cheers for your help. User error strikes again!

I appreciate the ultra quick response.

**Comment by ghost91-** [comment]
Cool, perfect, closing this then :)
