### ISSUE TITLE
Issue on V9

### ISSUE THREAD

**Issue by Ychabod** [ghost-fvtt/fxmaster#168]
I'm on V9
Installed it, launch it on a simple world build.
I have tested effects in order, everything is fine, and when I activate clouds, I've changed some options, and suddenly the effect was gone

Now, even I uninstall it or desactivate it, and reinstall or activate it, it doesn't work, and produce 10% CPu usage, extreme lag on a map 50x50 for exemple, even when no effects activated

The filter seems working, but not the effect

**Comment by ghost91-** [comment]
Hey there @Ychabod, could you please fill out the template for bug reports instead writing it "free style"? In the template, I ask for a lot of important details which will help with figuring out what the problem is and it saves me time by not having to ask for all of those details myself in every single bug report. I’ll just close the ticket, please create a new one using the template :)
