### ISSUE TITLE
FXMaster Errors Out and Does Nothing (v9)

### ISSUE THREAD

**Issue by raistlain** [ghost-fvtt/fxmaster#184]
### Expected Behavior

FXMaster Magic Hat is present and the macros in the compendium are usable. 

### Current Behavior

No Magic Hat appears in the left of the screen and there is no way to access any of the settings. The macros do not work and nothing happens. 

### Steps to Reproduce

1. Update to V9 from a v8 world
2. Update FXMaster to v.2.2.2
3. Load world and wait for base system version to update
4. Confirm FXMaster is running and enabled
5. See nothing present and that FXMaster macros do not work

### Context

Two errors are encountered. The first is that FXMaster extends an unknown class and does not appear to load. The second is that when clicking one of the macros present in the compendium, I receive an error saying "FXMASTER is not defined [No packages detected]" The module is installed, is activated in the game world, and the macros are present in the compendium. See images below for details pulled from the developer console:

![Error 1](https://user-images.githubusercontent.com/44714176/150252662-cf763ab5-f5fd-4afe-9b5a-8cd098da8a67.png)
![Error 2](https://user-images.githubusercontent.com/44714176/150252667-aa2de9aa-8c6a-4d89-9cd7-3e4ed62eaf8e.png)

### Version

v2.2.2

### Foundry VTT Version

v9 build 242

### Operating System

Windows

### Browser / App

Native Electron App

### Game System

pf2e v3.2.2.10054

### Relevant Modules

Token Magic FX v0.5.3, Settings Extender v 1.2.0, PF2e Toolbox, Combat Utility Belt v1.8.1

**Comment by ghost91-** [comment]
This sounds like something went wrong with updating FXMaster. Could you please check in your user data folder, in the modules folder, in the `fxmaster` folder, that the following file exists: `libs/filters/pixi-filters.js`.

I had a report in the past where for some weird reason, the file was missing, which resulted in a very similar issue. If that file is indeed missing, please try uninstalling and  reinstalling FXMaster.

**Comment by Ychabod** [comment]
Same issue, same version of foundry and module, with a new world and only Fxmaster activated, no magic hat

**Comment by ghost91-** [comment]
Hi @Ychabod, could you please provide me with the additional information i asked for above? Otherwise it’s basically impossible for me to do anything about this.

I think in the other case where a similar issue happened, it was related to the user using a cloud sync service for their user data folder. In that case it was google drive, but it can probably also happen with any other cloud sync. Are you using anything of that sort? If so, that’s generally a bad idea as it is prone to creating corrupted data. The general recommendation is to not sync the user data folder with a cloud Service, or at least not run it at the same time foundry is running.

Another potential cause might be anti virus software interfering. Are you running any anti virus software?

**Comment by raistlain** [comment]
@ghost91- I confirmed that the pixi-filters.js file was missing which was likely the root cause of the error. I updated the module again today and it seems to have worked correctly. Thanks for your help.

**Comment by ghost91-** [comment]
Closing this as the original issue is fixed. The issue of @Ychabod is being tracked at #192.
