### ISSUE TITLE
FX master crashes the browser

### ISSUE THREAD

**Issue by Nedrapter** [ghost-fvtt/fxmaster#243]
### Expected Behavior

To not crash the browser

### Current Behavior

When swapping to some scenes, the loading of the scenes gets stuck at 100% and the browser becomes unresponsive. It doesn't happen on all scenes, but I haven't found anything in common to those it happens. There's no error in the console. By using Find the Culprit, it came down to FX master. Weirdly enough it happens even with libwrapper off, which FX master has dependency on.

### Steps to Reproduce

I cannot reproduce it on every scene. Some scenes do it, others do not.

### Context

It only happens on some scenes. it doesn't rotate (if a scene does it once it will always do it)

### Version

2.4

### Foundry VTT Version

9.242

### Operating System

Windows 10

### Browser / App

Chrome, Firefox, Other

### Game System

dnd5e

**Comment by ghost91-** [comment]
Thanks for the report @Nedrapter, could you please export one of the problematic scenes and upload the corresponding json file here? If possible, also include any assets used by the scene (background image, tiles, etc.). You can bundle it as a zip file.

**Comment by Nedrapter** [comment]
[fvtt-Scene-the-multiportal-water.zip](https://github.com/ghost-fvtt/fxmaster/files/8370529/fvtt-Scene-the-multiportal-water.zip)
[baileywiki portal 2000x6000 100pxl water.zip](https://github.com/ghost-fvtt/fxmaster/files/8370544/baileywiki.portal.2000x6000.100pxl.water.zip)
That's the json file of the scene and the canvas background image.

**Comment by ghost91-** [comment]
Just took a quick look at the JSON, and I can already see what is likely the problem. The scene has a fog effect with a density of 16. 16 is _much_ too high. That will create a _ton_ of particles, which is just too much work for the browser, so it freezes.

Probably this is scene / effect is from the time before version 2.0 of fxmaster. I recommend to simply remove the effects from these scenes. In order to do that, follow the instructions at https://github.com/ghost-fvtt/fxmaster#-warning-regarding-large-scenes.

I will take a more detailed look this evening, but I am pretty sure this is the issue.

Probably this is scene / effect is from the time before version 2.0 of fxmaster. I recommend to simply remove the effects from these scenes. In order to do that, follow the instructions at https://github.com/ghost-fvtt/fxmaster#-warning-regarding-large-scenes.

I will take a more detailed look this evening, but I am pretty sure this is the issue.

**Comment by Nedrapter** [comment]
Removing the effects with the script did solve the issue. Is there a way to do this automatically or en-mass? I have hundreds of scenes....

**Comment by ghost91-** [comment]
Are those scenes in your scenes directory, or in compendium packs?

**Comment by Nedrapter** [comment]
Mainly in compendium packs.

**Comment by ghost91-** [comment]
If you want to remove the effects from _all_ compendium packs, use this:
```js
const removeWeatherEffectsFromSceneCompendium = async (pack) => {
  const type = pack.metadata.type ?? pack.metadata.entity;
  if (type !== "Scene") {
    return;
  }

  const wasLocked = pack.locked;
  await pack.configure({ locked: false });

  const scenes = await pack.getDocuments();

  for (const scene of scenes) {
    await scene.unsetFlag("fxmaster", "effects");
  }

  await pack.configure({ locked: wasLocked });
};

for (const pack of game.packs) {
  await removeWeatherEffectsFromSceneCompendium(pack);
}
```

Be aware that this will also remove the effects in compendium packs provided by modules and the system. If you want to skip those, add the following line before `await removeWeatherEffectsFromSceneCompendium(pack);`:
```js
  if(pack.metadata.package !== "world") continue;
```

To delete all effects from scenes in the scene directory, use
```js
for (const scene of game.scenes) {
  await scene.unsetFlag("fxmaster", "effects");
}
```

I'll close this issue as this seems to be a data issue, not a problem with FXMaster itself.
