### ISSUE TITLE
Ability to display weather effects on top of map pins

### ISSUE THREAD

**Issue by Nieeeb** [ghost-fvtt/fxmaster#261]
### Description

I've made a world map with some journal pins that blend into the map itself. Put having the clouds go behind them makes them stick out like a sore thumb and ruins the effect

**Comment by ghost91-** [comment]
Unfortunately, this is not possible without restructuring the the order of the core canvas layers / groups:

The notes layer is currently part of the interface group, but the weather effects are part of the primary group, so that they can be below the sight layer (and a couple of other technical reasons). Putting the effects layer into the interface group would make them appear over the sight layer, which is undesirable. And they really don’t belong into the interface group anyways, IMO.

While not technically difficult, restructuring the order of core layers / groups is not in scope for FXMaster. Perfect Vision does some restructuring, so you might want to take a look if it improves your situation. If not, creating a small module that just moves the notes layer into the primary group and below the effects should be pretty easy. But be aware that this would also move them under other stuff in the effects group, such as lighting, sight, walls (that one is probably irrelevant).
