### ISSUE TITLE
Local weather effects?

### ISSUE THREAD

**Issue by Gurrgel** [ghost-fvtt/fxmaster#311]
### Description

Would it be at all possible to add a feature where either Weather Blocker drawings could block only a specific weather effect, or where you could add a specific weather effects with local settings only over a specific drawing.

I fully understand if it isn't possible, but it would be great if Perfect Visions's ability to use separate light settings locally for a drawing could be coupled with a similar option from this module to use similarly different weather effects for different areas of the same scene, i.e. rain in one area and fog in another, rather than the current option where you can only choose to remove weather effects from some areas...

**Comment by ghost91-** [comment]
I can’t speak about Weather Blocker, since the integration is made on their side, not on the side of FXMaster. And unless you want integration with the levels module, I think it’s mostly obsolete anyways, since FXMaster provides its own functionality for masking weather effects.

Regarding applying masks only to specific weather effects, see #163
